### PR TITLE
Fix intermittent Jason.DecodeError in stream

### LINKED ISSUE #60: Intermittent Jason.DecodeError while streaming output
During periods of high volume, and in particular when using some of the gpt-3.5 series models, OpenAI will occasionally split events into multiple chunks.  The current approach of splitting each line with "\n" assumes the chunks are complete events.  However, this is not always the case.

```elixir
** (Jason.DecodeError) unexpected end of input at position 18
    (jason 1.4.0) lib/jason.ex:92: Jason.decode!/2
    (elixir 1.15.6) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.15.6) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (openai 0.6.1) lib/openai/stream.ex:57: anonymous fn/1 in OpenAI.Stream.new/1
    (elixir 1.15.6) lib/stream.ex:1626: Stream.do_resource/5
    (elixir 1.15.6) lib/stream.ex:690: Stream.run/1
```

### PR DESCRIPTION
**Pull request by bfolkens**
Fixes #60 

This patch reworks the OpenAI.Stream module to first accumulate the chunks, then parse them into events in order to avoid orphaned events, thereby leading to a Jason.DecodeError

Includes `Bypass` and `Plug` libraries (test env only) to enable testing of event stream.

### CODE REVIEW

**Comment by thiagomajesk** [comment]
Hi @mgallo is there anything preventing this from getting merged? It seems this bug is quite problematic. Also thanks for the hard work @bfolkens 💪

**Comment by mgallo** [comment]
> Hi, @mgallo is there anything preventing this from getting merged?

@thiagomajesk Sorry, nothing but super busy months 😫 .. I'll take a look at this ASAP.

**Comment by charif-workera** [comment]
Hi @bfolkens, this doesn't cover the following case that happens with assistants v2. In `lib/openai/stream.ex` for the parse_data function it breaks with the following data. I will take a look at it as well, but maybe it will help you also. 

```
"event: thread.run.created\ndata: {\"id\":\"run_NqTZL9RK5cu9T5n6KV394fo4\",\"object\":\"thread.run\",\"created_at\":1721218990,\"assistant_id\":\"asst_KJElmrVFoaAqM4phoRefhSuP\",\"thread_id\":\"thread_so0XakgtnQFuZ2s38ssAVtvE\",\"status\":\"queued\",\"started_at\":null,\"expires_at\":1721219590,\"cancelled_at\":null,\"failed_at\":null,\"completed_at\":null,\"required_action\":null,\"last_error\":null,\"model\":\"gpt-4o\",\"instructions\":\"You are a helpful professor. You will guide this learner in a concise, enthusiastic, and motivating way. You only expand if needed. The message you send back is just what the learner will read in the communication with you. Never mention the commands directly in a message!\",\"tools\":[],\"tool_resources\":{\"code_interpreter\":{\"file_ids\":[]}},\"metadata\":{},\"temperature\":0.01,\"top_p\":1.0,\"max_completion_tokens\":null,\"max_prompt_tokens\":null,\"truncation_strategy\":{\"type\":\"auto\",\"last_messages\":null},\"incomplete_details\":null,\"usage\":null,\"response_format\":\"auto\",\"tool_choice\":\"auto\",\"parallel_tool_calls\":true}"
```

**Comment by bfolkens** [comment]
> Hi @bfolkens, this doesn't cover the following case that happens with assistants v2. In `lib/openai/stream.ex` for the parse_data function it breaks with the following data. I will take a look at it as well, but maybe it will help you also.
> 
> ```
> "event: thread.run.created\ndata: {\"id\":\"run_NqTZL9RK5cu9T5n6KV394fo4\",\"object\":\"thread.run\",\"created_at\":1721218990,\"assistant_id\":\"asst_KJElmrVFoaAqM4phoRefhSuP\",\"thread_id\":\"thread_so0XakgtnQFuZ2s38ssAVtvE\",\"status\":\"queued\",\"started_at\":null,\"expires_at\":1721219590,\"cancelled_at\":null,\"failed_at\":null,\"completed_at\":null,\"required_action\":null,\"last_error\":null,\"model\":\"gpt-4o\",\"instructions\":\"You are a helpful professor. You will guide this learner in a concise, enthusiastic, and motivating way. You only expand if needed. The message you send back is just what the learner will read in the communication with you. Never mention the commands directly in a message!\",\"tools\":[],\"tool_resources\":{\"code_interpreter\":{\"file_ids\":[]}},\"metadata\":{},\"temperature\":0.01,\"top_p\":1.0,\"max_completion_tokens\":null,\"max_prompt_tokens\":null,\"truncation_strategy\":{\"type\":\"auto\",\"last_messages\":null},\"incomplete_details\":null,\"usage\":null,\"response_format\":\"auto\",\"tool_choice\":\"auto\",\"parallel_tool_calls\":true}"
> ```

Thanks for the fixture, that helps.  I just made a test case and will take a look.

**Comment by stuartjohnpage** [comment]
I can confirm this fixes things on our end. It also looks like something has changed recently - this used to be intermittent, and now it's pretty much constant.

**Comment by bfolkens** [comment]
This is still WIP - had to jump through a bunch of hurdles because OpenAI doesn't send SSE's to spec, so I want to spend some time working through the tests.  There's also a strange hackney issue popping up occasionally, so I'd like to narrow that down too.

**Comment by stuartjohnpage** [comment]
I think it's worth noting: since the OpenAI outages this morning, the intermittent nature of the problem this fixed has become constant. The PR, as it is, does fix that issue.

**Comment by bfolkens** [comment]
I deployed this new iteration to a medium-traffic website this afternoon and it's been running without a hitch.  Certainly curious of anyone else's experiences for the recent commit since this is turning into a rather large diff.

File: test/openai/stream_test.exs [hunk 1]
```diff
@@ -39,7 +48,6 @@ defmodule OpenAI.StreamTest do
         |> Enum.to_list()
 
       assert [
-               %{"choices" => [], "code" => 400, "status" => :error},
```
Comment (bfolkens) [inline test/openai/stream_test.exs]: Just a heads up I changed the error format slightly.  I'm not sure if we should keep that contract for the user but considering this is a pre rel 1 release I pulled this out since it seemed like a bit of a work-around given the way the stream worked in the previous versions.

**Review by mgallo — APPROVED** [review]
@bfolkens looks good to me, I'm going to merge it and release it with the patch `0.6.2`. Thanks again for your efforts! 🚀
